### ISSUE TITLE
nose package is not being installed

### ISSUE THREAD

**Issue by korigod** [conda-forge/holopy-feedstock#15]
**Issue:**
`nosetests` run outside of `conda` environment. Tests immediately fail because `python2.7` is being used. If `nose` is not installed at all, tests fail because `nosetests` binary is not found.

**Solution:**
Install `nose` `conda` package in the same environment. It's obvious it can be added to `meta.yaml`, however, I'm not sure to what section of `requirements` (`build` or `run`) and is it possible without pumping the package version so I haven't filed the PR and opened an issue instead.

The alternative solution is to add information about `nose` package to the docs (`dev_tutorial`) but the package size is only about 200 Kb so I think it's ok to install it for everyone.

**Comment by barkls** [comment]
Fixed in #24
